### ISSUE TITLE
Sample missing in readme

### ISSUE THREAD

**Issue by sergiandreplace** [cholojuanito/credit_card_type_detector#1]
Hi

I think there is something missing in the *Usage* section of your readme. There is only an `import` line, and it's missing and example of current usage.

I'm on my phone now, but maybe I can do a PR later on.

Thanks for the library!

**Comment by cholojuanito** [comment]
Oh you're right! I guess I left that out, I'll get that fixed as soon as my semester ends (this next week)

**Comment by cholojuanito** [comment]
Closing this since I added one awhile ago.
