### ISSUE TITLE
This package is not identifying JCB card type on the mobile side.

### ISSUE THREAD

**Issue by RUPESHJHA06** [cholojuanito/credit_card_type_detector#14]
@cholojuanito The package is having issues identifying JCB card Type on the mobile side.

**Comment by cholojuanito** [comment]
Please include any code or examples of how you've diagnosed the issue when you make Issues about stuff like this.

**Comment by RUPESHJHA06** [comment]
@cholojuanito I have added the card number as 3337000000000008 and it was not recognized as a JCB card type on the mobile app.

**Comment by cholojuanito** [comment]
This is not a bug then. The default values for JCB cards are taken from [this Wikipedia page](https://en.wikipedia.org/wiki/Payment_card_number) and from the Braintree repo this package is based off of. If you need support for a different set of Patterns for built in cards then you can use the new functions that were made available in version 3.0.0
